-- Dr. Alvin — seed data
-- Generated from the live dr-alvin.com catalogue by scripts/import-catalog.mjs.
-- Mirrors src/data/products.ts so the app looks identical with or without Supabase.
-- Rerunnable: existing products and categories are replaced.

delete from public.products;
delete from public.categories;

insert into public.categories (slug, name, blurb, step, sort_order) values
  ('cleansers',     'Cleansers',   'Lift the day off without stripping the barrier.',                     'cleanse', 1),
  ('soaps',         'Soaps',       'The bars that built the brand — kojic, arbutin, glutathione.',        'cleanse', 2),
  ('toners',        'Toners',      'Rebalance after cleansing and prep skin for actives.',                'tone',    3),
  ('serums',        'Serums',      'High-concentration actives for a single, specific job.',              'treat',   4),
  ('creams',        'Creams',      'Seal in moisture and hold the results you have earned.',              'treat',   5),
  ('sets',          'Sets',        'A full routine in one box, sequenced for you.',                       'treat',   6),
  ('sun-care',      'Sun care',    'Non-negotiable in tropical sun, especially on actives.',              'protect', 7),
  ('body-and-hair', 'Body & hair', 'The same formulations, scaled past the face.',                        'protect', 8);

with c as (select id, slug from public.categories)
insert into public.products
  (slug, name, summary, description, actives, category_id, step, price_centavos, compare_at_centavos, size_label, how_to_use, skin_concerns, is_best_seller, is_featured, featured_order, in_stock, rating_average, rating_count, image_tone, images)
values
  ('all-in-1-maintenance-cream', 'All in 1 Maintenance Cream', 'Dr. Alvin® All-in-1 Maintenance Cream is formulated to deliver a wide range of skincare benefits.', 'Dr. Alvin® All-in-1 Maintenance Cream is formulated to deliver a wide range of skincare benefits. The cream’s unique blend of moisturizers, brightening agents, and antioxidants works synergistically to improve skin texture, even out skin tone, and provide a radiant, youthful complexion. Whether used as a daily moisturizer or as part of an intensive skincare regimen, this cream offers a holistic approach to skincare maintenance.',
   '{}'::text[], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Uneven tone','Dryness','Fine lines'],
   true, true, 1, true, 0, 0, 'sand', array['/products/all-in-1-maintenance-cream-1.webp']),
  ('gluta-kojic-acid-soap', 'Gluta-Kojic Acid Soap', 'Gluta-Kojic Soap: Illuminate Your Skin’s Radiance.', 'Gluta-Kojic Soap: Illuminate Your Skin’s Radiance. Our soap is meticulously crafted to bring you the ultimate solution for achieving brighter, clearer, and more radiant skin. Infused with the powerful combination of Glutathione and Kojic Acid, this soap delivers unparalleled results, helping you unveil your skin’s natural luminosity with every use.',
   array['Kojic Acid','Glutathione'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   true, true, 2, true, 0, 0, 'marigold', array['/products/gluta-kojic-acid-soap-1.webp','/products/gluta-kojic-acid-soap-2.webp']),
  ('whitening-sunscreen-cream-gel-spf50-pa', 'Whitening Sunscreen Cream-Gel SPF50+ PA++++, 10 g', 'Dr. Alvin Whitening Sunscreen Cream-Gel SPF 50+ PA++++ offers powerful broad-spectrum protection against UVA and UVB rays while brighteni…', 'Dr. Alvin Whitening Sunscreen Cream-Gel SPF 50+ PA++++ offers powerful broad-spectrum protection against UVA and UVB rays while brightening the skin with Niacinamide, which helps to even out skin tone and reduce dark spots. Its lightweight, non-greasy formula absorbs quickly, leaving the skin feeling fresh and hydrated, thanks to the soothing and moisturizing properties of Aloe Vera extract. Perfect for daily use, it provides comprehensive sun protection without compromising comfort.',
   array['Niacinamide','SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   10800, null, '10 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Dryness','Fine lines','Sun damage'],
   true, true, 3, true, 0, 0, 'marigold', array['/products/whitening-sunscreen-cream-gel-spf50-pa-1.webp','/products/whitening-sunscreen-cream-gel-spf50-pa-2.webp','/products/whitening-sunscreen-cream-gel-spf50-pa-3.webp']),
  ('all-in-1-maintenance-set', 'All in 1 Maintenance Set', 'This set is designed to help maintain the rejuvenated skin achieved through Rejuvenating Sets.', 'This set is designed to help maintain the rejuvenated skin achieved through Rejuvenating Sets. It provides continuous care with gentle ingredients to keep the skin healthy and radiant.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   30000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Sensitivity'],
   true, true, 4, true, 0, 0, 'violet', array['/products/all-in-1-maintenance-set-1.webp','/products/all-in-1-maintenance-set-2.webp']),
  ('kojic-acid-soap-5', 'Kojic Acid Soap, 135 g × 2', 'Ideal for long-term use, providing an extended supply for continuous skin care.', 'Ideal for long-term use, providing an extended supply for continuous skin care.',
   array['Kojic Acid'], (select id from c where slug='soaps'), 'cleanse',
   13000, null, '135 g × 2',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   true, true, 5, true, 0, 0, 'marigold', array['/products/kojic-acid-soap-5-1.webp','/products/kojic-acid-soap-5-2.webp']),
  ('all-in-1-maintenance-toner-2', 'All in 1 Maintenance Toner, 120 ml', 'Formulated with safe and natural ingredients, Dr. Alvin® All in One Maintenance Toner can be used as a maintenance toner after skin rejuv…', 'Formulated with safe and natural ingredients, Dr. Alvin® All in One Maintenance Toner can be used as a maintenance toner after skin rejuvenation treatments. It is developed to reduce the visibility of dark spots, discoloration, and age spots, while also providing skin hydration. Incorporating this product into your daily skincare routine can help you achieve optimal results.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   17000, null, '120 ml',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Uneven tone','Dryness'],
   true, true, 6, true, 0, 0, 'violet', array['/products/all-in-1-maintenance-toner-2-1.webp','/products/all-in-1-maintenance-toner-2-2.webp']),
  ('colors-of-empire-color-changing-lip-balm', 'Colors of Empire – Color Changing Lip Balm', 'Colors of Empire – Color Changing Lip Balm is a uniquely formulated lip balm that adapts its color based on the wearer’s pH, providing a…', 'Colors of Empire – Color Changing Lip Balm is a uniquely formulated lip balm that adapts its color based on the wearer’s pH, providing a personalized tint. Enriched with nourishing ingredients like Shea Butter and Vitamin E, it offers hydration and a hint of color suitable for everyday wear. Variants available: 001 Blush Pink 002 Peach 003 Fuchsia 004 Magenta',
   array['Vitamin E'], (select id from c where slug='body-and-hair'), 'protect',
   17500, null, '3.2 g',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], array['Dryness'],
   false, false, null, true, 0, 0, 'leaf', array['/products/colors-of-empire-color-changing-lip-balm-1.webp']),
  ('kojic-acid-skin-lightening-lotion-with-beautamin-complex-and-vitamins-b3-b5-c-and-e', 'Kojic Acid Skin Lightening Lotion with Beautamin Complex and Vitamins B3, B5, C and E', 'Dr. Alvin® Kojic Acid Skin Lightening Lotion is a moisturizing body lotion formulated with Beautamin Complex and a blend of Vitamins B3,…', 'Dr. Alvin® Kojic Acid Skin Lightening Lotion is a moisturizing body lotion formulated with Beautamin Complex and a blend of Vitamins B3, B5, C, and E to help improve the appearance of dull and uneven-looking skin. Enriched with Kojic Acid Dipalmitate, Niacinamide, Glycolic Acid, and Lactic Acid, the formula helps promote a brighter and more radiant-looking complexion while maintaining skin hydration. The lotion spreads easily and leaves the skin feeling soft, smooth, and moisturized without a heavy feel. With added broad-spectrum UV filters, it also helps protect the skin from daily sun exposure that may contribute to skin darkening and uneven skin appearance.',
   array['Kojic Acid','Niacinamide','Vitamin C','AHA'], (select id from c where slug='body-and-hair'), 'protect',
   0, null, '120 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], array['Dark spots','Uneven tone','Dryness','Sun damage'],
   false, false, null, false, 0, 0, 'leaf', array['/products/kojic-acid-skin-lightening-lotion-with-beautamin-complex-and-vitamins-b3-b5-c-and-e-1.webp']),
  ('master-clean-toilet-bowl-cleaner-formulated-by-dr-alvin-research-institute', 'Master Clean (Toilet Bowl Cleaner) formulated by Dr. Alvin Research Institute', 'Master Clean (Toilet Bowl Cleaner) formulated by Dr. Alvin® Research Institute to provide maximum and superior disinfecting and cleaning…', 'Master Clean (Toilet Bowl Cleaner) formulated by Dr. Alvin® Research Institute to provide maximum and superior disinfecting and cleaning toilet bowls and other facilities. Master Clean – Toilet Bowl Cleaner effectively kills wide spectrum of disease-causing viruses and bacterias, including E. Coli which causes UTI, Salmonella Typhi which causes the dreaded Typhoid Fever and Candida Albicans which causes Vaginal infections.',
   '{}'::text[], (select id from c where slug='body-and-hair'), 'protect',
   18000, null, '500 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], '{}'::text[],
   false, false, null, false, 0, 0, 'leaf', array['/products/master-clean-toilet-bowl-cleaner-formulated-by-dr-alvin-research-institute-1.webp','/products/master-clean-toilet-bowl-cleaner-formulated-by-dr-alvin-research-institute-2.webp']),
  ('maxigrow-minoxidil-5-topical-spray', 'MaxiGrow (Minoxidil 5%) Topical Spray', 'Introducing Dr. Alvin’s Minoxidil 5% Spray, the cutting-edge solution for hair loss you’ve been waiting for.', 'Introducing Dr. Alvin’s Minoxidil 5% Spray, the cutting-edge solution for hair loss you’ve been waiting for. Formulated with clinically proven Minoxidil 5%, this innovative spray revitalizes hair follicles, promotes thicker, fuller hair growth, and reawakens confidence like never before.',
   array['Minoxidil 5%'], (select id from c where slug='body-and-hair'), 'protect',
   119500, null, '60 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], '{}'::text[],
   false, false, null, true, 0, 0, 'leaf', array['/products/maxigrow-minoxidil-5-topical-spray-1.webp']),
  ('maxigrow-naturals-hair-recovery-conditioner', 'MaxiGrow Naturals Hair Recovery Conditioner', 'Dr. Alvin® MaxiGrow Naturals Hair Recovery Conditioner, helps hair to recover from environmental factors by deeply nourishing the scalp,…', 'Dr. Alvin® MaxiGrow Naturals Hair Recovery Conditioner, helps hair to recover from environmental factors by deeply nourishing the scalp, aids in stimulating hair follicles, and strengthens hair for a revitalized, resilient appearance. Directions for Use: After shampooing with Dr. Alvin® MaxiGrow Naturals Hair Recovery Shampoo, squeeze out excess water. Apply generous amount of Dr. Alvin® MaxiGrow Naturals Hair Recovery Conditioner to scalp and hair. Leave on for 3-5 minutes to allow the ingredients to penetrate deeply. Rinse thoroughly with water. Use regularly for optimal results.',
   '{}'::text[], (select id from c where slug='body-and-hair'), 'protect',
   18000, null, '500 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], '{}'::text[],
   false, false, null, false, 0, 0, 'leaf', array['/products/maxigrow-naturals-hair-recovery-conditioner-1.webp']),
  ('maxigrow-naturals-hair-recovery-shampoo', 'MaxiGrow Naturals Hair Recovery Shampoo', 'Dr. Alvin® MaxiGrow Naturals Hair Recovery Shampoo, helps hair to recover from environmental factors by deeply nourishing the scalp, aids…', 'Dr. Alvin® MaxiGrow Naturals Hair Recovery Shampoo, helps hair to recover from environmental factors by deeply nourishing the scalp, aids in stimulating hair follicles, and strengthens hair for a revitalized, resilient appearance. Directions for use: Wet your har thoroughly. Apply a generous amount of Dr. Alvin® MaxiGrow Naturals Hair Recovery Shampoo to your scalp and hair. Massage gently into the scalp, working up a rish lather. Ensure even distribution through the length of your hair. Leave on for 1-2 minutes to allow the ingredients to penetrate deeply. Rinse thoroughly with water. Use regularly for optimal results.',
   '{}'::text[], (select id from c where slug='body-and-hair'), 'protect',
   18000, null, '500 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], array['Uneven tone'],
   false, false, null, false, 0, 0, 'leaf', array['/products/maxigrow-naturals-hair-recovery-shampoo-1.webp']),
  ('peeling-lotion', 'Peeling Lotion', 'Dr. Alvin® Peeling Lotion is an exfoliating body lotion formulated with a blend of Alpha Hydroxy Acids (AHAs) to help improve the appeara…', 'Dr. Alvin® Peeling Lotion is an exfoliating body lotion formulated with a blend of Alpha Hydroxy Acids (AHAs) to help improve the appearance of dull and rough skin. The formula helps promote a smoother, softer, and more refined-looking skin surface while maintaining skin moisture. Enriched with Lactic Acid, Glycolic Acid, Malic Acid, and Mandelic Acid, this lotion helps support the skin’s natural exfoliation process, contributing to a brighter and more even-looking appearance. With added Glycerin, Betaine, and Sodium Lactate, it also helps maintain hydration and skin comfort during use. Designed for regular body care, the lightweight lotion leaves the skin feeling smoother, moisturized, and refreshed.',
   array['AHA'], (select id from c where slug='body-and-hair'), 'protect',
   0, null, '120 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, false, 0, 0, 'leaf', array['/products/peeling-lotion-1.webp']),
  ('underam-lightening-deodorant-original-formula-with-niacinamide', 'Underam Lightening Deodorant Original Formula with Niacinamide', 'Dr. Alvin® Underarm Lightening Deodorant Original Formula with Niacinamide is a daily-use deodorant designed to help control underarm odo…', 'Dr. Alvin® Underarm Lightening Deodorant Original Formula with Niacinamide is a daily-use deodorant designed to help control underarm odor while providing skin-conditioning benefits for the underarm area. Formulated with Aluminum Chlorohydrate, it helps reduce underarm wetness and provides long-lasting deodorant protection. Enriched with Niacinamide, 3-O-Ethyl Ascorbic Acid (Vitamin C Derivative), and Centella Asiatica Extract, the formula helps improve the appearance of underarm skin, leaving it looking smoother, more even-toned, and healthy-looking with continued use. Its alcohol-free formula is gentle on the skin and suitable for everyday underarm care.',
   array['Niacinamide','Vitamin C'], (select id from c where slug='body-and-hair'), 'protect',
   15000, null, '50 ml',
   array['Apply to clean skin or hair as directed on the label.','Use daily for best results.'], array['Dark spots','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'leaf', array['/products/underam-lightening-deodorant-original-formula-with-niacinamide-1.webp']),
  ('beautamin-c-body-wash', 'Beautamin C Body Wash', 'Experience brighter, smoother, and healthier-looking skin all over with Dr. Alvin® Beautamin C Body Wash.', 'Experience brighter, smoother, and healthier-looking skin all over with Dr. Alvin® Beautamin C Body Wash. This revitalizing formula gently cleanses while infusing your skin with combined brightening power of Vitamin C (3-O-Ethyl Ascorbic Acid) and Niacinamide. This actives also helps even out skin tone, restore glow, and protect against environmental stress. Enriched with Glycerin and D-Panthenol, it keeps your skin soft, hydrated, and refreshed after every bath.',
   array['Niacinamide','Vitamin C'], (select id from c where slug='cleansers'), 'cleanse',
   0, null, '',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, false, 0, 0, 'chalk', array['/products/beautamin-c-body-wash-1.webp']),
  ('ceramoist-barrier-repair-cleanser', 'Ceramoist Barrier Repair Cleanser', 'Specially formulated to support the skin’s natural moisture barrier, Ceramoist Skin Barrier Repair Cleanser gently cleanses while helping…', 'Specially formulated to support the skin’s natural moisture barrier, Ceramoist Skin Barrier Repair Cleanser gently cleanses while helping maintain a healthier, more resilient complexion. Its mild formula is designed to cleanse effectively without stripping the skin, leaving it feeling comfortable, balanced, and refreshed. The skin’s protective barrier, made up of ceramides and essential lipids, plays a key role in keeping moisture in and external stressors out. When this barrier feels weakened, skin may appear dry, sensitive, or dull. Regular use of a gentle, barrier-supporting cleanser helps keep skin feeling smooth, hydrated, and naturally radiant.',
   array['Ceramides'], (select id from c where slug='cleansers'), 'cleanse',
   25000, null, '120 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'chalk', array['/products/ceramoist-barrier-repair-cleanser-1.webp']),
  ('colors-of-empire-brightening-micellar-cleansing-oil-2', 'Colors of Empire – Brightening Micellar Cleansing Oil, 100 ml', 'Colors of Empire – Brightening Micellar Cleansing Oil is a facial cleanser designed to effectively remove makeup, including long-wearing…', 'Colors of Empire – Brightening Micellar Cleansing Oil is a facial cleanser designed to effectively remove makeup, including long-wearing formulas, along with dirt and surface impurities. Formulated with micellar technology, it gently lifts away buildup while helping maintain the skin’s natural moisture. Enriched with skin-conditioning oils, it leaves the skin feeling clean, soft, and refreshed, with a more radiant-looking appearance after use.',
   '{}'::text[], (select id from c where slug='cleansers'), 'cleanse',
   35000, null, '100 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dark spots','Dryness'],
   false, false, null, true, 0, 0, 'chalk', array['/products/colors-of-empire-brightening-micellar-cleansing-oil-2-1.webp']),
  ('colors-of-empire-brightening-micellar-cleansing-oil', 'Colors of Empire – Brightening Micellar Cleansing Oil, 100 ml', 'Colors of Empire – Brightening Micellar Cleansing Oil is a luxurious facial cleanser that offers a double cleansing effect.', 'Colors of Empire – Brightening Micellar Cleansing Oil is a luxurious facial cleanser that offers a double cleansing effect. It effectively removes waterproof makeup, dirt, and impurities while nourishing the skin with essential oils and brightening agents. Its innovative micellar technology ensures gentle yet thorough cleansing without stripping the skin of its natural moisture.',
   '{}'::text[], (select id from c where slug='cleansers'), 'cleanse',
   35000, null, '100 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dark spots','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'chalk', array['/products/colors-of-empire-brightening-micellar-cleansing-oil-1.webp']),
  ('gluta-papaya-facial-foam-cleanser', 'Gluta-Papaya Facial Foam Cleanser', 'Dr. Alvin Gluta-Papaya Foam Wash is the perfect solution for achieving clear and radiant skin.', 'Dr. Alvin Gluta-Papaya Foam Wash is the perfect solution for achieving clear and radiant skin. Our unique formula has Niacinamide, which helps to reduce the appearance of dark spots and even out skin tone. With the aid of Carica Papaya Enzyme, the skin is naturally and gently exfoliated, appearing smooth and young. Although Glutathione helps to brighten the skin and lessen the appearance of wrinkles, Kojic Acid aids to decrease melanin synthesis and lighten dark spots. The experience has also been enhanced by the addition of a delicate, pleasant scent. With Dr. Alvin Gluta-Papaya Foam Wash, enjoy the ideal fusion of antioxidant-rich nutrients and luscious foamy action.',
   array['Kojic Acid','Glutathione','Niacinamide','Papaya Enzyme'], (select id from c where slug='cleansers'), 'cleanse',
   30000, null, '115 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dark spots','Uneven tone','Dryness','Sensitivity','Fine lines'],
   false, false, null, true, 0, 0, 'chalk', array['/products/gluta-papaya-facial-foam-cleanser-1.webp','/products/gluta-papaya-facial-foam-cleanser-2.webp']),
  ('kojic-acid-micropeeling-foam-wash', 'Kojic Acid Micropeeling Foam Wash', 'Dr. Alvin Kojic Acid Micropeeling Foam Wash is the perfect solution for your skin care needs!', 'Dr. Alvin Kojic Acid Micropeeling Foam Wash is the perfect solution for your skin care needs! This foaming cleanser harnesses the power of five key ingredients to give you a skin-smoothing, brightening, and refreshing experience. Niacinamide helps to reduce the appearance of dark spots and uneven skin tone. Kojic Acid works to lighten and brighten skin. Carica Papaya Enzyme, a naturally derived ingredient, breaks down dead skin cells and pollutants, leaving your skin feeling clean and looking fresh. To refresh the skin and lessen inflammation, menthol offers a cooling feeling. Citric acid aids in exfoliation, skin brightening, and wrinkle reduction. With Dr. Alvin Kojic Acid Micropeeling Foam Wash, you can enjoy a fresh, glowing complexion with every use.',
   array['Kojic Acid','Niacinamide','Papaya Enzyme'], (select id from c where slug='cleansers'), 'cleanse',
   30000, null, '115 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Dark spots','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'chalk', array['/products/kojic-acid-micropeeling-foam-wash-1.webp','/products/kojic-acid-micropeeling-foam-wash-2.webp']),
  ('multifruit-peel-ahabhatxa-facial-wash', 'Multifruit Peel AHA+BHA+TXA Facial Wash', 'It contains Pure and Natural Fruit Extracts that promote skin deep-cleansing and moisture balancing for natural glass-look skin.', 'It contains Pure and Natural Fruit Extracts that promote skin deep-cleansing and moisture balancing for natural glass-look skin.',
   array['AHA','BHA','Tranexamic Acid'], (select id from c where slug='cleansers'), 'cleanse',
   12000, null, '60 ml',
   array['Massage onto damp skin for 30 seconds.','Rinse thoroughly and pat dry.','Follow with toner while skin is still damp.'], array['Acne','Dryness'],
   false, false, null, true, 0, 0, 'chalk', array['/products/multifruit-peel-ahabhatxa-facial-wash-1.webp']),
  ('beautamin-a-0-025-tretinoin-0-025', 'Beautamin A 0.025% (Tretinoin 0.025%)', 'Approved indication: Used for the treatment of acne vulgaris and for conditions which cause difficulties in the formation of skin’s strat…', 'Approved indication: Used for the treatment of acne vulgaris and for conditions which cause difficulties in the formation of skin’s stratum corneum such as mottled hyperpigmentation, roughness, and fine wrinkling of photodamaged skin.',
   array['Tretinoin'], (select id from c where slug='creams'), 'treat',
   15000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'sand', array['/products/beautamin-a-0-025-tretinoin-0-025-1.webp']),
  ('beautamin-a-0-05-tretinoin-0-05', 'Beautamin A 0.05% (Tretinoin 0.05%)', 'Approved indication: Used for the treatment of acne vulgaris and for conditions which cause difficulties in the formation of skin’s strat…', 'Approved indication: Used for the treatment of acne vulgaris and for conditions which cause difficulties in the formation of skin’s stratum corneum such as mottled hyperpigmentation, roughness, and fine wrinkling of photodamaged skin.',
   array['Tretinoin'], (select id from c where slug='creams'), 'treat',
   20000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'sand', array['/products/beautamin-a-0-05-tretinoin-0-05-1.webp']),
  ('ceramoist-barrier-repair-cream-2', 'Ceramoist Barrier Repair Cream', 'An excellent hypoallergenic moisturizer for those with sensitive skin.', 'An excellent hypoallergenic moisturizer for those with sensitive skin. It’s like a soothing blanket for your face. The five essential ceramides help repair the skin’s protective barrier, so it can lock in moisture and keep irritants out. Think of it as rebuilding your skin’s fence. This cream gives your skin a deep drink of hydration that lasts, leaving it feeling soft and healthy.”',
   array['Ceramides'], (select id from c where slug='creams'), 'treat',
   10000, null, '15 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'sand', array['/products/ceramoist-barrier-repair-cream-2-1.webp']),
  ('kojic-acid-micropeeling-cream', 'Kojic Acid Micropeeling Cream', 'Dr. Alvin Kojic Acid Micropeeling Cream is expertly crafted to provide gentle yet effective exfoliation, promoting a brighter and more ev…', 'Dr. Alvin Kojic Acid Micropeeling Cream is expertly crafted to provide gentle yet effective exfoliation, promoting a brighter and more even skin tone. Enriched with kojic acid, this micropeeling cream targets hyperpigmentation and dark spots while refining the skin’s texture, resulting in a smoother and more radiant complexion.',
   array['Kojic Acid'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'sand', array['/products/kojic-acid-micropeeling-cream-1.webp']),
  ('multifruit-peel-ahabhatxa-cream', 'Multifruit Peel AHA+BHA+TXA Cream', 'Dr. Alvin® Multifruit Peel AHA+BHA+TXA Cream is formulated with a blend of multiple fruit acids, beta-hydroxy acids, and tranexamic acid…', 'Dr. Alvin® Multifruit Peel AHA+BHA+TXA Cream is formulated with a blend of multiple fruit acids, beta-hydroxy acids, and tranexamic acid to deliver a powerful exfoliating and brightening effect. This cream works to remove dead skin cells, unclog pores, and reduce the appearance of dark spots and hyperpigmentation. The result is smoother, clearer, and more radiant skin with a glass-like finish.',
   array['AHA','BHA','Tranexamic Acid'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Dryness'],
   false, false, null, true, 0, 0, 'sand', array['/products/multifruit-peel-ahabhatxa-cream-1.webp']),
  ('rejumax-duo-cream-hydroquinone-2-tretinoin-0-025', 'Rejumax Duo Cream (Hydroquinone 2% + Tretinoin 0.025%)', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells for brighter complexion.',
   array['Tretinoin','Hydroquinone'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'sand', array['/products/rejumax-duo-cream-hydroquinone-2-tretinoin-0-025-1.webp']),
  ('rejumax-plain-cream-hydroquinone-2', 'Rejumax Plain Cream (Hydroquinone 2%)', 'Approved indication: Used in the treatment of skin in hyperpigmentation condition such as melasma, chloasma, freckles & lentigines (small…', 'Approved indication: Used in the treatment of skin in hyperpigmentation condition such as melasma, chloasma, freckles & lentigines (small macules that resembles freckles) and post-inflammatory marks from psoriasis and eczema.',
   array['Hydroquinone'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots'],
   false, false, null, false, 0, 0, 'sand', array['/products/rejumax-plain-cream-hydroquinone-2-1.webp']),
  ('rejuvenating-advance-cream-hydroquinone-4-tretinoin-0-025', 'Rejuvenating Advance Cream (Hydroquinone 4% + Tretinoin 0.025%)', 'Approved indication: Used in the treatment of mild cases of acne and skin hyperpigmentation', 'Approved indication: Used in the treatment of mild cases of acne and skin hyperpigmentation',
   array['Tretinoin','Hydroquinone'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Sensitivity','Fine lines'],
   false, false, null, true, 0, 0, 'sand', array['/products/rejuvenating-advance-cream-hydroquinone-4-tretinoin-0-025-1.webp']),
  ('rejuvenating-duo-cream-hydroquinone-2-tretinoin-0-025', 'Rejuvenating Duo Cream (Hydroquinone 2% + Tretinoin 0.025%)', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells for brighter complexion.',
   array['Tretinoin','Hydroquinone'], (select id from c where slug='creams'), 'treat',
   10000, null, '10 g',
   array['Apply a pea-sized amount to clean skin.','Use at night, or as directed for your regimen step.','Never skip sunscreen the following morning.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'sand', array['/products/rejuvenating-duo-cream-hydroquinone-2-tretinoin-0-025-1.webp']),
  ('aha-max-megadose-serum', 'AHA MAX Megadose Serum', 'Dr. Alvin® AHA MAX Megadose Serum is formulated with a blend of alpha hydroxy acids (AHAs) and skin-conditioning ingredients to support g…', 'Dr. Alvin® AHA MAX Megadose Serum is formulated with a blend of alpha hydroxy acids (AHAs) and skin-conditioning ingredients to support gentle exfoliation and overall skin revitalization. It helps remove surface buildup of dead skin cells, promoting a smoother-looking texture and more even-looking tone. With consistent use, skin appears brighter, more refined, and visibly refreshed, while the look of fine lines and discoloration is improved.',
   array['AHA'], (select id from c where slug='serums'), 'treat',
   16000, null, '15 ml',
   array['Apply two or three drops to clean, dry skin.','Press in rather than rubbing.','Follow with sunscreen every morning.'], array['Dark spots','Uneven tone','Dryness','Sensitivity','Fine lines'],
   false, false, null, true, 0, 0, 'violet', array['/products/aha-max-megadose-serum-1.webp','/products/aha-max-megadose-serum-2.webp']),
  ('beautamin-c-serum', 'Beautamin C Serum', 'Dr. Alvin® Beautamin C Serum is a lightweight facial serum formulated with Vitamin C, Niacinamide, Hyaluronic Acid, and a blend of Alpha…', 'Dr. Alvin® Beautamin C Serum is a lightweight facial serum formulated with Vitamin C, Niacinamide, Hyaluronic Acid, and a blend of Alpha Hydroxy Acids (AHAs). Designed as part of a daily skincare routine, it helps improve the appearance of skin radiance, smoothness, and hydration while supporting a brighter and more even-looking complexion. Its fast-absorbing formula leaves the skin feeling soft, refreshed, and moisturized without a heavy or sticky feel.',
   array['Niacinamide','Vitamin C'], (select id from c where slug='serums'), 'treat',
   0, null, '',
   array['Apply two or three drops to clean, dry skin.','Press in rather than rubbing.','Follow with sunscreen every morning.'], array['Dark spots','Uneven tone','Dryness','Oiliness','Fine lines'],
   false, false, null, false, 0, 0, 'violet', array['/products/beautamin-c-serum-1.webp']),
  ('dr-peel-serum-hydroquinone-4-tretinoin-0-05', 'Dr. Peel Serum (Hydroquinone 4% + Tretinoin 0.05%)', 'Approved indication: used for the treatment of moderate to severe cases of acne and skin hyperpigmentation.', 'Approved indication: used for the treatment of moderate to severe cases of acne and skin hyperpigmentation.',
   array['Tretinoin','Hydroquinone'], (select id from c where slug='serums'), 'treat',
   16500, null, '15 ml',
   array['Apply two or three drops to clean, dry skin.','Press in rather than rubbing.','Follow with sunscreen every morning.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'violet', array['/products/dr-peel-serum-hydroquinone-4-tretinoin-0-05-1.webp']),
  ('pure-vitamin-c-fresh-release-cell-activator-serum-mix', 'Pure Vitamin C Fresh Release Cell Activator Serum Mix', 'Dr. Alvin® Pure Vitamin C Fresh Release Cell Activator Serum Mix features a unique formulation that combines the brightening power of Vit…', 'Dr. Alvin® Pure Vitamin C Fresh Release Cell Activator Serum Mix features a unique formulation that combines the brightening power of Vitamin C with skin-soothing and hydrating ingredients. The serum is activated by mixing the liquid and powder components, ensuring that the Vitamin C remains fresh and effective. This powerful antioxidant serum helps to brighten the complexion, reduce pigmentation, and protect against environmental damage.',
   array['Vitamin C'], (select id from c where slug='serums'), 'treat',
   20000, null, '20 ml',
   array['Apply two or three drops to clean, dry skin.','Press in rather than rubbing.','Follow with sunscreen every morning.'], array['Dark spots','Dryness'],
   false, false, null, true, 0, 0, 'violet', array['/products/pure-vitamin-c-fresh-release-cell-activator-serum-mix-1.webp']),
  ('all-in-1-maintenance-toner', 'All in 1 Maintenance Toner, 60 ml', 'Formulated with safe and natural ingredients, Dr. Alvin® All in One Maintenance Toner can be used as a maintenance toner after skin rejuv…', 'Formulated with safe and natural ingredients, Dr. Alvin® All in One Maintenance Toner can be used as a maintenance toner after skin rejuvenation treatments. It is developed to reduce the visibility of dark spots, discoloration, and age spots, while also providing skin hydration. Incorporating this product into your daily skincare routine can help you achieve optimal results.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   11000, null, '60 ml',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, true, 0, 0, 'violet', array['/products/all-in-1-maintenance-toner-1.webp','/products/all-in-1-maintenance-toner-2.webp']),
  ('hair-recovery-shampoo-conditioner-bundle', 'Hair Recovery Shampoo + Conditioner (Bundle)', 'Introducing the Dr. Alvin Shampoo & Conditioner Bundle – Your ultimate duo for stronger and healthier hair!!', 'Introducing the Dr. Alvin Shampoo & Conditioner Bundle – Your ultimate duo for stronger and healthier hair!! Get BOTH for just ₱250! Dr. Alvin® – Trusted for Skin, Now Your Go-To for Hair! #HairCareGoals #AffordableLuxury #DrAlvinHairCare',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   25000, null, 'Bundle',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], '{}'::text[],
   false, false, null, false, 0, 0, 'violet', array['/products/hair-recovery-shampoo-conditioner-bundle-1.webp']),
  ('kojic-acid-micropeeling-set', 'Kojic Acid Micropeeling Set', 'For those looking to further enhance their skincare routine, the Kojic Acid Set offers additional brightening and exfoliating benefits.', 'For those looking to further enhance their skincare routine, the Kojic Acid Set offers additional brightening and exfoliating benefits. It helps in maintaining an even skin tone and reducing the appearance of dark spots.',
   array['Kojic Acid'], (select id from c where slug='sets'), 'treat',
   33000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Uneven tone'],
   false, false, null, false, 0, 0, 'violet', array['/products/kojic-acid-micropeeling-set-1.webp','/products/kojic-acid-micropeeling-set-2.webp']),
  ('kojic-acid-micropeeling-toner', 'Kojic Acid Micropeeling Toner', 'Dr. Alvin® Kojic Acid Toner is a revolutionary skincare solution designed to help you achieve a brighter, more radiant complexion.', 'Dr. Alvin® Kojic Acid Toner is a revolutionary skincare solution designed to help you achieve a brighter, more radiant complexion. This expertly formulated toner combines the power of kojic acid with other potent ingredients to gently exfoliate the skin, reduce hyperpigmentation, and promote a more even skin tone.',
   array['Kojic Acid'], (select id from c where slug='sets'), 'treat',
   11000, null, '60 ml',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, true, 0, 0, 'violet', array['/products/kojic-acid-micropeeling-toner-1.webp','/products/kojic-acid-micropeeling-toner-2.webp']),
  ('multifruit-peel-exfoliant-set', 'Multifruit Peel Exfoliant Set', 'This set harnesses the power of alpha hydroxy acids (AHA), beta hydroxy acids (BHA), and tranexamic acid (TXA) to provide a comprehensive…', 'This set harnesses the power of alpha hydroxy acids (AHA), beta hydroxy acids (BHA), and tranexamic acid (TXA) to provide a comprehensive peeling treatment. It helps exfoliate dead skin cells, unclog pores, and reduce pigmentation, leaving the skin smoother, brighter, and more even-toned.',
   array['AHA','BHA','Tranexamic Acid'], (select id from c where slug='sets'), 'treat',
   30000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Uneven tone'],
   false, false, null, true, 0, 0, 'violet', array['/products/multifruit-peel-exfoliant-set-1.webp','/products/multifruit-peel-exfoliant-set-2.webp']),
  ('papaya-cleansing-toner', 'Papaya Cleansing Toner', 'Dr. Alvin Papaya Cleansing Toner is a mild whitening cleanser, ideal if you have no acne or just mild acne from time to time.', 'Dr. Alvin Papaya Cleansing Toner is a mild whitening cleanser, ideal if you have no acne or just mild acne from time to time. Best for naturally fair skin that are looking to even out their skin tone. Promotes renewal and cell turnover the natural way.',
   array['Papaya Enzyme'], (select id from c where slug='sets'), 'treat',
   9000, null, '60 ml',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'violet', array['/products/papaya-cleansing-toner-1.webp','/products/papaya-cleansing-toner-2.webp']),
  ('rejuvenating-set-1', 'Rejuvenating Set #1', 'Embark on your rejuvenation journey with the Dr. Alvin Rejumax Set 1, the perfect starting point for sensitive skin or first-time users.', 'Embark on your rejuvenation journey with the Dr. Alvin Rejumax Set 1, the perfect starting point for sensitive skin or first-time users. This set gently reduces pigmentation, evens skin tone, and promotes cell renewal, revealing a brighter and smoother complexion.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   30000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Uneven tone','Sensitivity'],
   false, false, null, true, 0, 0, 'violet', array['/products/rejuvenating-set-1-1.webp','/products/rejuvenating-set-1-2.webp']),
  ('rejuvenating-set-2', 'Rejuvenating Set #2', 'Step up your skincare regimen with the Dr. Alvin Rejumax Set 2.', 'Step up your skincare regimen with the Dr. Alvin Rejumax Set 2. This set offers a moderate strength to tackle more stubborn pigmentation and fine lines, providing a more pronounced rejuvenating effect.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   30500, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, false, 0, 0, 'violet', array['/products/rejuvenating-set-2-1.webp','/products/rejuvenating-set-2-2.webp']),
  ('rejuvenating-set-3', 'Rejuvenating Set #3', 'For those with resilient skin needing more intensive treatment, the Dr. Alvin Rejumax Set 3 delivers enhanced rejuvenation.', 'For those with resilient skin needing more intensive treatment, the Dr. Alvin Rejumax Set 3 delivers enhanced rejuvenation. This potent set effectively combats severe pigmentation, deeper lines, and uneven skin texture.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   31000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Uneven tone'],
   false, false, null, false, 0, 0, 'violet', array['/products/rejuvenating-set-3-1.webp','/products/rejuvenating-set-3-2.webp']),
  ('rejuvenating-set-4', 'Rejuvenating Set #4', 'This set is formulated for significant skin issues, providing potent exfoliation and brightening.', 'This set is formulated for significant skin issues, providing potent exfoliation and brightening. It effectively reduces moderate to severe pigmentation and fine lines, yielding clearer and more youthful skin.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   31500, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'violet', array['/products/rejuvenating-set-4-1.webp','/products/rejuvenating-set-4-2.webp']),
  ('rejuvenating-set-5', 'Rejuvenating Set #5', 'The most potent set in the series, designed for experienced users.', 'The most potent set in the series, designed for experienced users. It offers maximum treatment for severe pigmentation and deep wrinkles, providing comprehensive skin renewal and anti-aging benefits.',
   '{}'::text[], (select id from c where slug='sets'), 'treat',
   33000, null, '1 set',
   array['Follow the numbered order printed on the box.','Introduce actives gradually over the first week.','Wear SPF 50+ every morning for the whole course.'], array['Dark spots','Acne','Fine lines'],
   false, false, null, true, 0, 0, 'violet', array['/products/rejuvenating-set-5-1.webp','/products/rejuvenating-set-5-2.webp']),
  ('alpha-arbutin-soap', 'Alpha Arbutin Soap', 'Dr. Alvin® Alpha Arbutin Soap is derived from Bearberry extract; made from the leaves of the bearberry shrub which naturally lightens and…', 'Dr. Alvin® Alpha Arbutin Soap is derived from Bearberry extract; made from the leaves of the bearberry shrub which naturally lightens and brightens skin. It helps the skin to get lighter and promotes an even skin tone. Alpha Arbutin works to whiten your skin by inhibiting the enzyme tyrosinase which is responsible for the production of melanin.',
   array['Alpha Arbutin'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Uneven tone'],
   false, false, null, false, 0, 0, 'marigold', array['/products/alpha-arbutin-soap-1.webp','/products/alpha-arbutin-soap-2.webp']),
  ('calamansi-soap', 'Calamansi Soap', 'Enriched with natural calamansi extract, this cleansing bar helps improve the appearance of uneven skin tone while gently removing surfac…', 'Enriched with natural calamansi extract, this cleansing bar helps improve the appearance of uneven skin tone while gently removing surface impurities and dead skin cells. Its refreshing formula supports fresher‑feeling skin and helps maintain natural freshness, leaving skin looking healthy, smooth, and revitalized with regular use. Suitable for daily cleansing. Results may vary.',
   array['Calamansi'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Uneven tone'],
   false, false, null, false, 0, 0, 'marigold', array['/products/calamansi-soap-1.webp','/products/calamansi-soap-2.webp']),
  ('glutathione-brightening-soap-with-niacinamide', 'Glutathione Brightening Soap with Niacinamide', 'This soap is crafted with Vitamin B3 (Niacinamide) to boost brightening efficacy that helps in achieving softer, smoother, and glowing skin.', 'This soap is crafted with Vitamin B3 (Niacinamide) to boost brightening efficacy that helps in achieving softer, smoother, and glowing skin. Use regularly as daily cleanser to achieve lighter and radiant complexion.',
   array['Glutathione','Niacinamide'], (select id from c where slug='soaps'), 'cleanse',
   6000, null, '',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Dryness'],
   false, false, null, true, 0, 0, 'marigold', array['/products/glutathione-brightening-soap-with-niacinamide-1.webp','/products/glutathione-brightening-soap-with-niacinamide-2.webp']),
  ('kojic-acid-soap', 'Kojic Acid Soap, 135 g', 'Experience the transformative power of Dr. Alvin’s Kojic Acid Soap and embark on a journey to radiant, luminous skin.', 'Experience the transformative power of Dr. Alvin’s Kojic Acid Soap and embark on a journey to radiant, luminous skin. From its humble beginnings as one of the first two soaps distributed by Dr. Alvin to its status as a beloved classic in the skincare world, this soap embodies the essence of our commitment to quality, efficacy, and tradition.',
   array['Kojic Acid'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   false, false, null, true, 0, 0, 'marigold', array['/products/kojic-acid-soap-1.webp','/products/kojic-acid-soap-2.webp']),
  ('kojic-acid-soap-2', 'Kojic Acid Soap, 65 g', 'Ideal for travel or trying the product for the first time, this portable size lets you experience the benefits of Dr. Alvin® Kojic Acid S…', 'Ideal for travel or trying the product for the first time, this portable size lets you experience the benefits of Dr. Alvin® Kojic Acid Soap wherever you go.',
   array['Kojic Acid'], (select id from c where slug='soaps'), 'cleanse',
   3400, null, '65 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   false, false, null, true, 0, 0, 'marigold', array['/products/kojic-acid-soap-2-1.webp']),
  ('kojic-acid-soap-3', 'Kojic Acid Soap, 65 g × 3', 'Unlock the secret to a brighter you with Dr. Alvin’s Kojic Acid Soap.', 'Unlock the secret to a brighter you with Dr. Alvin’s Kojic Acid Soap. This travel-friendly size is perfect for discovering the difference it can make for your skin.',
   array['Kojic Acid'], (select id from c where slug='soaps'), 'cleanse',
   9700, null, '65 g × 3',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   false, false, null, true, 0, 0, 'marigold', array['/products/kojic-acid-soap-3-1.webp','/products/kojic-acid-soap-3-2.webp']),
  ('kojic-acid-soap-4', 'Kojic Acid Soap, 90 g × 3', 'Experience the transformative lightening power of Dr. Alvin Kojic Acid Soap in a balanced choice for regular use, ensuring consistent res…', 'Experience the transformative lightening power of Dr. Alvin Kojic Acid Soap in a balanced choice for regular use, ensuring consistent results.',
   array['Kojic Acid'], (select id from c where slug='soaps'), 'cleanse',
   13000, null, '90 g × 3',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots'],
   false, false, null, true, 0, 0, 'marigold', array['/products/kojic-acid-soap-4-1.webp','/products/kojic-acid-soap-4-2.webp']),
  ('oatmeal-soap-with-honey', 'Oatmeal Soap with Honey', 'Reveal your skin’s natural radiance with Dr. Alvin Oatmeal Soap with Honey, featuring gentle exfoliation from oatmeal and deep moisturiza…', 'Reveal your skin’s natural radiance with Dr. Alvin Oatmeal Soap with Honey, featuring gentle exfoliation from oatmeal and deep moisturization from honey.',
   array['Colloidal Oatmeal','Honey'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'marigold', array['/products/oatmeal-soap-with-honey-1.webp','/products/oatmeal-soap-with-honey-2.webp']),
  ('papaya-whitening-soap-2', 'Papaya Whitening Soap, 135 g', 'Unlock the natural way of skin lightening with Dr. Alvin® Papaya Whitening Soap.', 'Unlock the natural way of skin lightening with Dr. Alvin® Papaya Whitening Soap. This travel-friendly size is perfect for discovering the difference it can make for your skin.',
   array['Papaya Enzyme'], (select id from c where slug='soaps'), 'cleanse',
   4800, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Dryness'],
   false, false, null, true, 0, 0, 'marigold', array['/products/papaya-whitening-soap-2-1.webp','/products/papaya-whitening-soap-2-2.webp']),
  ('papaya-whitening-soap', 'Papaya Whitening Soap, 65 g', 'Unlock the natural way of lightening skin with Dr. Alvin® Papaya Whitening Soap.', 'Unlock the natural way of lightening skin with Dr. Alvin® Papaya Whitening Soap. This travel-friendly size is perfect for discovering the difference it can make for your skin.',
   array['Papaya Enzyme'], (select id from c where slug='soaps'), 'cleanse',
   2100, null, '65 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Dryness'],
   false, false, null, true, 0, 0, 'marigold', array['/products/papaya-whitening-soap-1.webp','/products/papaya-whitening-soap-2.webp']),
  ('placenta-soap', 'Placenta Soap', 'Formulated to cleanse and help to improve the appearance of your skin.', 'Formulated to cleanse and help to improve the appearance of your skin. Our Placenta soap is meticulously developed to harness the power of placental protein and its revitalizing qualities helping skin to maintain a healthy, beautiful complexion.',
   array['Placenta Extract'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Dryness','Fine lines'],
   false, false, null, true, 0, 0, 'marigold', array['/products/placenta-soap-1.webp','/products/placenta-soap-2.webp']),
  ('tea-tree-soap', 'Tea Tree Soap', 'This tea tree oil and leaves are saponified with coconut oil to create a gentle aroma and provide benefits for acne-prone skin.', 'This tea tree oil and leaves are saponified with coconut oil to create a gentle aroma and provide benefits for acne-prone skin. Its natural oil helps prevent irritation/ irritants from minor skin concerns.',
   array['Tea Tree Oil'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Acne','Uneven tone','Sensitivity'],
   false, false, null, false, 0, 0, 'marigold', array['/products/tea-tree-soap-1.webp','/products/tea-tree-soap-2.webp']),
  ('vitamin-c-soap', 'Vitamin C Soap', 'Formulated with a stable form of Vitamin C, this soap helps improve the look of uneven skin tone while cleansing the skin thoroughly.', 'Formulated with a stable form of Vitamin C, this soap helps improve the look of uneven skin tone while cleansing the skin thoroughly. Its antioxidant-rich formula supports a clearer, fresher-looking complexion, leaving skin visibly brighter and smoother with regular use.',
   array['Vitamin C'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Uneven tone'],
   false, false, null, true, 0, 0, 'marigold', array['/products/vitamin-c-soap-1.webp','/products/vitamin-c-soap-2.webp','/products/vitamin-c-soap-3.webp']),
  ('whitening-black-soap', 'Whitening Black Soap', 'Dr. Alvin Whitening Black Soap uses powerful cleansing agents that works together to remove dirt, oil, and impurities without stripping y…', 'Dr. Alvin Whitening Black Soap uses powerful cleansing agents that works together to remove dirt, oil, and impurities without stripping your skin’s natural moisture barrier. Added with Licorice Root Extract that helps soothes irritation and even out skin tone.',
   array['Activated Charcoal'], (select id from c where slug='soaps'), 'cleanse',
   9000, null, '135 g',
   array['Work into a lather with water rather than rubbing the bar on skin.','Leave on for 30 seconds, then rinse well.','Use once daily to start, twice once skin adjusts.'], array['Dark spots','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'marigold', array['/products/whitening-black-soap-1.webp','/products/whitening-black-soap-2.webp']),
  ('color-adapt-tinted-sunscreen-spf50-pa', 'Color Adapt Tinted Sunscreen SPF50+ PA++++', 'Dr. Alvin Color Adapt Tinted Sunscreen SPF50+ PA++++ is a tone-adapting sunscreen designed to provide both sun protection and cosmetic co…', 'Dr. Alvin Color Adapt Tinted Sunscreen SPF50+ PA++++ is a tone-adapting sunscreen designed to provide both sun protection and cosmetic coverage. Formulated with iron oxide, it helps protect the skin from high-energy visible (HEV) light and blue light coming from phones, gadgets, and electronic devices. Its lightweight formula offers a mattifying finish, helping reduce shine while masking pigmentation and uneven skin tone. This fast-absorbing sunscreen blends naturally with the skin without leaving a white cast, making it ideal for daily wear.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   10800, null, '10 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Oiliness','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/color-adapt-tinted-sunscreen-spf50-pa-1.webp','/products/color-adapt-tinted-sunscreen-spf50-pa-2.webp','/products/color-adapt-tinted-sunscreen-spf50-pa-3.webp']),
  ('cosmentix-oil-control-absorbing-film', 'Cosmentix – Oil Control Absorbing Film', 'Cosmentix Oil Control Absorbing Film is your secret weapon for a shine-free, refreshed complexion throughout the day.', 'Cosmentix Oil Control Absorbing Film is your secret weapon for a shine-free, refreshed complexion throughout the day. These ultra-thin films are formulated with powerful ingredients and materials to absorb excess oil without disrupting your makeup.',
   '{}'::text[], (select id from c where slug='sun-care'), 'protect',
   12000, null, '100 sheets',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Oiliness'],
   false, false, null, false, 0, 0, 'marigold', array['/products/cosmentix-oil-control-absorbing-film-1.webp','/products/cosmentix-oil-control-absorbing-film-2.webp']),
  ('dewy-moisturizing-sunscreen-cream-spf50-pa-with-placenta-and-vitamin-e', 'Dewy Moisturizing Sunscreen Cream SPF50+ PA++++ with Placenta and Vitamin E', 'Dr. Alvin Dewy Moisturizing Sunscreen Cream SPF50+ PA++++ is a hydrating sunscreen formulated with BioPlacenta (plant-derived placenta) a…', 'Dr. Alvin Dewy Moisturizing Sunscreen Cream SPF50+ PA++++ is a hydrating sunscreen formulated with BioPlacenta (plant-derived placenta) and Vitamin E to support skin regeneration and improve skin elasticity. This moisturizing sunscreen provides deep hydration, brightening, and anti-aging benefits, helping improve skin firmness and overall skin tone. Its cosmetic dewy finish gives the skin a radiant glow while also functioning as a light foundation and moisturizer, making it suitable for adults looking for added skin care benefits with their sun protection.',
   array['Vitamin E','SPF 50+','Placenta Extract'], (select id from c where slug='sun-care'), 'protect',
   10800, null, '10 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Dryness','Fine lines','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/dewy-moisturizing-sunscreen-cream-spf50-pa-with-placenta-and-vitamin-e-1.webp','/products/dewy-moisturizing-sunscreen-cream-spf50-pa-with-placenta-and-vitamin-e-2.webp','/products/dewy-moisturizing-sunscreen-cream-spf50-pa-with-placenta-and-vitamin-e-3.webp']),
  ('glutathione-lotion-10x-brightening-with-niacinamide-plus-fresh-and-satin-feel-technology-and-spf30-pa', 'Glutathione Lotion 10x Brightening with Niacinamide (Plus Fresh and Satin-Feel Technology and SPF30 PA++++)', 'Dr. Alvin® Glutathione Lotion 10x Brightening with Niacinamide is a lightweight body lotion formulated to help moisturize the skin while…', 'Dr. Alvin® Glutathione Lotion 10x Brightening with Niacinamide is a lightweight body lotion formulated to help moisturize the skin while providing daily sun protection with SPF30 PA++++. Enriched with Niacinamide and Glutathione, the formula helps improve the appearance of dull-looking skin and promotes a brighter, more radiant-looking complexion. Its Fresh & Satin-Feel Technology provides a smooth, comfortable finish that leaves the skin feeling soft, moisturized, and refreshed without a heavy or greasy feel. With added Panthenol, Betaine, and Glycerin, this lotion helps maintain skin hydration and supports smooth, healthy-looking skin for everyday use.',
   array['Glutathione','Niacinamide','SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   19900, null, '120 ml',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Dryness','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/glutathione-lotion-10x-brightening-with-niacinamide-plus-fresh-and-satin-feel-technology-and-spf30-pa-1.webp']),
  ('papaya-whitening-body-lotion-with-natural-papain-enyme-plus-beautamin-complex-and-spf20-pa', 'Papaya Whitening Body Lotion with Natural Papain Enyme plus Beautamin Complex and SPF20 PA++++', 'Dr. Alvin® Papaya Whitening Body Lotion is a moisturizing body lotion formulated with Natural Papain Enzyme, Beautamin Complex, and SPF20…', 'Dr. Alvin® Papaya Whitening Body Lotion is a moisturizing body lotion formulated with Natural Papain Enzyme, Beautamin Complex, and SPF20 PA++++ to help improve the appearance of dull-looking skin while providing daily sun protection. Enriched with Niacinamide, Papain Enzyme, Vitamins B3, B5, C, and E, the formula helps promote a brighter-looking, smoother, and more radiant complexion. Its moisturizing blend helps maintain skin hydration, leaving the skin feeling soft, smooth, and comfortable throughout the day. With added UV filters, the lotion helps protect the skin from daily sun exposure that may contribute to uneven skin appearance.',
   array['Niacinamide','Vitamin C','Papaya Enzyme','SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   0, null, '120 ml',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Dryness','Sun damage'],
   false, false, null, false, 0, 0, 'marigold', array['/products/papaya-whitening-body-lotion-with-natural-papain-enyme-plus-beautamin-complex-and-spf20-pa-1.webp']),
  ('sunscreen-cream-spf50-pa-2', 'Sunscreen Cream SPF50 PA++++', 'Back by popular demand, the well-loved Dr. Alvin® Classic Sunscreen returns with an upgraded SPF50+ PA++++ formula to provide higher broa…', 'Back by popular demand, the well-loved Dr. Alvin® Classic Sunscreen returns with an upgraded SPF50+ PA++++ formula to provide higher broad-spectrum protection against UVA and UVB rays. Dr. Alvin® Sunscreen Cream SPF50+ PA++++ is a lightweight hybrid sunscreen that combines organic UV filters and Titanium Dioxide to help protect the skin from daily sun exposure. Formulated with Niacinamide, Panthenol, and Vitamin E, it helps maintain skin hydration while leaving the skin feeling smooth and comfortable. Its non-greasy texture spreads easily and absorbs well without leaving a heavy or sticky feeling, making it suitable for everyday use.',
   array['Niacinamide','Vitamin E','SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   9800, null, '10 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dryness','Fine lines','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-cream-spf50-pa-2-1.webp','/products/sunscreen-cream-spf50-pa-2-2.webp','/products/sunscreen-cream-spf50-pa-2-3.webp']),
  ('sunscreen-cream-spf50-pa', 'Sunscreen Cream SPF50+ PA++++', 'Dr. Alvin Sunscreen Cream SPF50+ PA++++ is a premium sun protection cream designed with an ultra-high SPF50+ rating and PA++++ to provide…', 'Dr. Alvin Sunscreen Cream SPF50+ PA++++ is a premium sun protection cream designed with an ultra-high SPF50+ rating and PA++++ to provide superior defense against the harmful effects of UVA and UVB rays. Formulated with a blend of advanced ingredients, this sunscreen not only protects but also nourishes the skin, ensuring a radiant and healthy complexion. Suitable for all skin types, including sensitive skin, it offers long-lasting protection, making it perfect for daily use.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   30000, null, '50 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Sensitivity','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-cream-spf50-pa-1.webp']),
  ('sunscreen-cream-spf50-pa-egg', 'Sunscreen Cream SPF50+ PA++++ (Egg)', 'Dr. Alvin Sunscreen Cream SPF50+ PA++++ is a premium sun protection cream designed with an ultra-high SPF50+ rating and PA++++ to provide…', 'Dr. Alvin Sunscreen Cream SPF50+ PA++++ is a premium sun protection cream designed with an ultra-high SPF50+ rating and PA++++ to provide superior defense against the harmful effects of UVA and UVB rays. Formulated with a blend of advanced ingredients, this sunscreen not only protects but also nourishes the skin, ensuring a radiant and healthy complexion. Suitable for all skin types, including sensitive skin, it offers long-lasting protection, making it perfect for daily use.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   30000, null, '50 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dryness','Sensitivity','Fine lines','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-cream-spf50-pa-egg-1.webp']),
  ('sunscreen-lotion-spf-50-pa-egg', 'Sunscreen Lotion SPF 50+ PA ++++ (Egg)', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole…', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole body. This innovative formula blends seamlessly, leaving no visible white cast. It is fast-absorbing, non-greasy formula feels weightless on your skin, makes it perfect for extended wear.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   35000, null, '100 ml',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dryness','Oiliness','Fine lines','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-lotion-spf-50-pa-egg-1.webp']),
  ('sunscreen-lotion-spf-50-pa-2', 'Sunscreen Lotion SPF 50+ PA ++++, 100 ml', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole…', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole body. This innovative formula blends seamlessly, leaving no visible white cast. It is fast-absorbing, non-greasy formula feels weightless on your skin, makes it perfect for extended wear.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   35000, null, '100 ml',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Oiliness','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-lotion-spf-50-pa-2-1.webp']),
  ('sunscreen-lotion-spf-50-pa', 'Sunscreen Lotion SPF 50+ PA ++++, 100 ml', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole…', 'Dr. Alvin Sunscreen Lotion offers broad-spectrum protection you can trust, in a convenient, larger size perfect for shielding your whole body. This innovative formula blends seamlessly, leaving no visible white cast. It is fast-absorbing, non-greasy formula feels weightless on your skin, makes it perfect for extended wear.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   35000, null, '100 ml',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Oiliness','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/sunscreen-lotion-spf-50-pa-1.webp']),
  ('vitamin-c-sunscreen-cream-gel-spf50-pa', 'Vitamin C Sunscreen Cream-Gel SPF50+ PA++++', 'Dr. Alvin Vitamin C Sunscreen Cream-Gel SPF50+ PA++++ is formulated with a stable form of Vitamin C (3-O-Ethyl Ascorbic Acid) that provid…', 'Dr. Alvin Vitamin C Sunscreen Cream-Gel SPF50+ PA++++ is formulated with a stable form of Vitamin C (3-O-Ethyl Ascorbic Acid) that provides antioxidant protection while helping boost collagen production and reduce signs of premature skin aging. This sunscreen helps protect the skin from UV-induced damage, supports skin brightening, and promotes a more youthful-looking complexion. Its gentle cream-gel texture allows smooth application on the face and even around the eye area, delivering both sun protection and skincare benefits.',
   array['Vitamin C','SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   30000, null, '50 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Sensitivity','Fine lines','Sun damage'],
   false, false, null, true, 0, 0, 'marigold', array['/products/vitamin-c-sunscreen-cream-gel-spf50-pa-1.webp','/products/vitamin-c-sunscreen-cream-gel-spf50-pa-2.webp','/products/vitamin-c-sunscreen-cream-gel-spf50-pa-3.webp']),
  ('whitening-sunscreen-cream-gel-spf50-pa-2', 'Whitening Sunscreen Cream-Gel SPF50+ PA++++, 50 g', 'Dr. Alvin Whitening Sunscreen Cream-Gel SPF 50+ PA++++ is a lightweight, non-greasy sunscreen designed to provide broad-spectrum protecti…', 'Dr. Alvin Whitening Sunscreen Cream-Gel SPF 50+ PA++++ is a lightweight, non-greasy sunscreen designed to provide broad-spectrum protection against harmful UVA and UVB rays while helping to lighten and brighten the skin. This innovative cream-gel formula ensures a smooth, even application that leaves the skin feeling fresh and hydrated without a sticky or oily residue. Suitable for all skin types, it is particularly effective for those seeking to protect their skin from sun damage while also achieving a more even skin tone.',
   array['SPF 50+'], (select id from c where slug='sun-care'), 'protect',
   30000, null, '50 g',
   array['Apply generously 15 minutes before sun exposure.','Reapply every two hours outdoors.','Use as the last step of the morning routine.'], array['Dark spots','Uneven tone','Dryness','Oiliness','Fine lines','Sun damage'],
   false, false, null, false, 0, 0, 'marigold', array['/products/whitening-sunscreen-cream-gel-spf50-pa-2-1.webp','/products/whitening-sunscreen-cream-gel-spf50-pa-2-2.webp','/products/whitening-sunscreen-cream-gel-spf50-pa-2-3.webp']),
  ('beautamin-c-toner', 'Beautamin C Toner', 'Refresh and revive your skin with Dr. Alvin® Beautamin C Toner—a lightweight, hydrating toner infused with a stable form of Vitamin C, mo…', 'Refresh and revive your skin with Dr. Alvin® Beautamin C Toner—a lightweight, hydrating toner infused with a stable form of Vitamin C, moisture-boosting ingredients, and skin-brightening actives. Designed to help remove residual impurities after cleansing while restoring hydration, this toner leaves the skin feeling clean, smooth, and energized.',
   array['Vitamin C'], (select id from c where slug='toners'), 'tone',
   0, null, '',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, false, 0, 0, 'leaf', array['/products/beautamin-c-toner-1.webp','/products/beautamin-c-toner-2.webp']),
  ('clarifying-toner-2', 'Clarifying Toner, 120 ml', 'Dr. Alvin® Clarifying Toner is a powerful, yet gentle toner that aims to cleanse the skin thoroughly, minimize the appearance of pores, a…', 'Dr. Alvin® Clarifying Toner is a powerful, yet gentle toner that aims to cleanse the skin thoroughly, minimize the appearance of pores, and provide a soothing effect.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   15000, null, '120 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'leaf', array['/products/clarifying-toner-2-1.webp','/products/clarifying-toner-2-2.webp']),
  ('clarifying-toner', 'Clarifying Toner, 60 ml', 'Dr. Alvin® Clarifying Toner is a powerful, yet gentle toner that aims to cleanse the skin thoroughly, minimize the appearance of pores, a…', 'Dr. Alvin® Clarifying Toner is a powerful, yet gentle toner that aims to cleanse the skin thoroughly, minimize the appearance of pores, and provide a soothing effect.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   10000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Uneven tone','Dryness','Sensitivity'],
   false, false, null, true, 0, 0, 'leaf', array['/products/clarifying-toner-1.webp','/products/clarifying-toner-2.webp']),
  ('green-papaya-cleansing-toner', 'Green Papaya Cleansing Toner', 'Dr. Alvin Green Papaya Cleansing Toner is formulated to cleanse and revitalize the skin.', 'Dr. Alvin Green Papaya Cleansing Toner is formulated to cleanse and revitalize the skin. Infused with the natural exfoliating properties of green papaya, this toner helps remove dead skin cells, revealing a fresher and more radiant complexion. Suitable for all skin types, it also prepares the skin for subsequent skincare steps by ensuring a thoroughly clean surface.',
   array['Papaya Enzyme'], (select id from c where slug='toners'), 'tone',
   10000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Uneven tone','Dryness'],
   false, false, null, true, 0, 0, 'leaf', array['/products/green-papaya-cleansing-toner-1.webp','/products/green-papaya-cleansing-toner-2.webp']),
  ('multifruit-peel-ahabhatxa-toner', 'Multifruit Peel AHA+BHA+TXA Toner', 'Dr. Alvin Multifruit Peel AHA+BHA+TXA Toner is formulated to offer a potent exfoliating experience with a blend of alpha-hydroxy acids (A…', 'Dr. Alvin Multifruit Peel AHA+BHA+TXA Toner is formulated to offer a potent exfoliating experience with a blend of alpha-hydroxy acids (AHAs) and beta-hydroxy acids (BHAs). This synergistic combination works to remove dead skin cells, unclog pores, and improve skin radiance. The inclusion of tranexamic acid helps to target hyperpigmentation and even out skin tone, providing a comprehensive solution for smoother, brighter, and more radiant skin.',
   array['AHA','BHA','Tranexamic Acid'], (select id from c where slug='toners'), 'tone',
   10000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone'],
   false, false, null, true, 0, 0, 'leaf', array['/products/multifruit-peel-ahabhatxa-toner-1.webp']),
  ('rejumax-1-toner', 'Rejumax 1 Toner', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   10500, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejumax-1-toner-1.webp']),
  ('rejumax-2-toner', 'Rejumax 2 Toner', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   11000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejumax-2-toner-1.webp']),
  ('rejumax-3-toner', 'Rejumax 3 Toner', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   11500, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejumax-3-toner-1.webp']),
  ('rejuvenating-advance-toner', 'Rejuvenating Advance Toner', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   12000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejuvenating-advance-toner-1.webp','/products/rejuvenating-advance-toner-2.webp','/products/rejuvenating-advance-toner-3.webp']),
  ('rejuvenating-prime-toner', 'Rejuvenating Prime Toner', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   11700, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejuvenating-prime-toner-1.webp','/products/rejuvenating-prime-toner-2.webp','/products/rejuvenating-prime-toner-3.webp']),
  ('rejuvenating-toner-no-1', 'Rejuvenating Toner No. 1', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   10500, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejuvenating-toner-no-1-1.webp','/products/rejuvenating-toner-no-1-2.webp','/products/rejuvenating-toner-no-1-3.webp']),
  ('rejuvenating-toner-no-2', 'Rejuvenating Toner No. 2', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   11000, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejuvenating-toner-no-2-1.webp','/products/rejuvenating-toner-no-2-2.webp','/products/rejuvenating-toner-no-2-3.webp']),
  ('rejuvenating-toner-no-3', 'Rejuvenating Toner No. 3', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging.', 'Approved indication: Used for the treatment of photo-aged skin, acne, premature wrinkles, and other signs of skin aging. It removes dark spots, blemishes, and dead skin cells.',
   '{}'::text[], (select id from c where slug='toners'), 'tone',
   11500, null, '60 ml',
   array['Sweep over the face with a cotton pad after cleansing.','Let it dry before applying cream or serum.','Use morning and night.'], array['Dark spots','Acne','Uneven tone','Fine lines'],
   false, false, null, true, 0, 0, 'leaf', array['/products/rejuvenating-toner-no-3-1.webp','/products/rejuvenating-toner-no-3-2.webp','/products/rejuvenating-toner-no-3-3.webp']);
